												/*TRIGGER 4*/
CREATE TRIGGER DEL ON ACTIONS AFTER DELETE
AS 
DECLARE @ACCOUNTNUMBER INT/*חשבון המבצע*/
DECLARE @AC_CODE INT /*סוג הפעולה*/
DECLARE @MONEY INT /*סכום הכסף של הפעולה*/
DECLARE @MONEY_PER_ACTION INT /*העלות הכספית של הפעולה*/
DECLARE @DEST INT 

SET @ACCOUNTNUMBER =(SELECT ACCOUNT_NUM FROM DELETED)
SET @AC_CODE = (SELECT ACTION_TYPE FROM DELETED)
SET @MONEY =(SELECT AMOUNT FROM DELETED)
SET @DEST =(SELECT DESTENATIONֹ_ACCOUNT_NUM FROM DELETED)
SET @MONEY_PER_ACTION =(SELECT ACTION_COST FROM ACTIONS_TYPE WHERE @AC_CODE = ACTION_CODE)


IF(@AC_CODE = 1)
BEGIN
UPDATE ACCOUNTS SET BALANCE = BALANCE - @MONEY + @MONEY_PER_ACTION WHERE @ACCOUNTNUMBER = ACCOUNT_NUM
UPDATE ACCOUNTS SET ACCOUNT_ACTIONS_NUM = ACCOUNT_ACTIONS_NUM - 1 WHERE @ACCOUNTNUMBER = ACCOUNT_NUM /* עדכון מספר פעולות שנעשו*/
END

IF(@AC_CODE = 2)
BEGIN
UPDATE ACCOUNTS SET BALANCE = BALANCE + @MONEY + @MONEY_PER_ACTION WHERE @ACCOUNTNUMBER = ACCOUNT_NUM
UPDATE ACCOUNTS SET ACCOUNT_ACTIONS_NUM = ACCOUNT_ACTIONS_NUM - 1 WHERE @ACCOUNTNUMBER = ACCOUNT_NUM /* עדכון מספר פעולות שנעשו*/
END

IF(@AC_CODE = 3)
BEGIN
UPDATE ACCOUNTS SET BALANCE = BALANCE + @MONEY + @MONEY_PER_ACTION WHERE @ACCOUNTNUMBER = ACCOUNT_NUM /*עדכון יתרת המבצע + העמלה*/
UPDATE ACCOUNTS SET BALANCE = BALANCE - @MONEY WHERE @DEST = ACCOUNT_NUM   /*עדכון יתרת היעד*/
UPDATE ACCOUNTS SET ACCOUNT_ACTIONS_NUM = ACCOUNT_ACTIONS_NUM - 1 WHERE @ACCOUNTNUMBER = ACCOUNT_NUM /* עדכון מספר פעולות שנעשו*/
END



DELETE FROM ACTIONS WHERE ACTION_CODE = 21