CREATE TRIGGER TR2 ON ACTIONS AFTER INSERT
AS
DECLARE @ACCOUNTNUMBER INT/*חשבון המבצע*/
DECLARE @AC_CODE INT /*סוג הפעולה*/
DECLARE @MONEY INT /*סכום הכסף של הפעולה*/
DECLARE @MONEY_PER_ACTION INT /*העלות הכספית של הפעולה*/
DECLARE @FRAME INT /*מסגרת*/
DECLARE @YTRA INT /*יתרת החשבון*/

SET @AC_CODE = (SELECT ACTION_TYPE FROM ACTIONS WHERE ACTION_CODE = @@IDENTITY)
SET @ACCOUNTNUMBER = (SELECT ACCOUNT_NUM FROM ACTIONS WHERE ACTION_CODE = @@IDENTITY)
SET @FRAME = (SELECT MSGERT FROM ACCOUNTS WHERE @ACCOUNTNUMBER = ACCOUNT_NUM)
SET @YTRA = (SELECT BALANCE FROM ACCOUNTS WHERE @ACCOUNTNUMBER = ACCOUNT_NUM)
SET @MONEY = (SELECT AMOUNT FROM ACTIONS WHERE ACTION_CODE = @@IDENTITY)
SET @MONEY_PER_ACTION = (SELECT ACTION_COST FROM ACTIONS_TYPE WHERE @AC_CODE = ACTION_CODE)

                                           /*WITHDRAW*/
IF(@AC_CODE = 2)
BEGIN
	IF(@MONEY < (@YTRA + @FRAME + @MONEY_PER_ACTION))
		BEGIN		
			UPDATE ACCOUNTS SET BALANCE = BALANCE - @MONEY - @MONEY_PER_ACTION WHERE @ACCOUNTNUMBER = ACCOUNT_NUM
			UPDATE ACCOUNTS SET ACCOUNT_ACTIONS_NUM = ACCOUNT_ACTIONS_NUM + 1 WHERE @ACCOUNTNUMBER = ACCOUNT_NUM
		END
	ELSE BEGIN PRINT 'AMIGOO , YOU DON"T HAVE ENOUGH DOLARRS' END
END
