CREATE TABLE CLIENTS
(
	NAME VARCHAR(20),/* שם הלקוח */
	ID VARCHAR(9),/* תעודת זהות לקוח*/
	ADDRESS1 VARCHAR(20), /* כתובת הלוקח */
);

CREATE TABLE ACCOUNTS
(
	CLIENT_ID VARCHAR(9),/*תעודת זהות לקוח*/
	ACCOUNT_NUM INT ,/*חשבון המבצע*/
	BALANCE INT, /* ייתרת החשבון */
	MSGERT INT, /* מסגרת החשבון */ 
	ACCOUNT_ACTIONS_NUM INT , /* מספר פעולות שנעשו בחשבון */

);

CREATE TABLE ACTIONS_TYPE
(
	ACTION_NAME VARCHAR(20), /*שם פעולה */ 
	ACTION_CODE INT , /*קוד פעולה */
	ACTION_COST INT,/*העלות הכספית של הפעולה*/
);

CREATE TABLE ACTIONS
(
	ACCOUNT_NUM INT,/* מספר חשבון שעליו בוצעה הפעולה*/
	DESTENATIONֹ_ACCOUNT_NUM INT, /* מספר חשבון היעד*/
	AMOUNT INT, /*סכום הכסף של הפעולה*/ 
	ACTION_TYPE INT,/*סוג הפעולה*/
	ACTION_CODE INT IDENTITY(1,1),
);

------------------------------------------------------------------------------------------------
							/* INSERT TO CLIENTS*/
INSERT INTO CLIENTS  (NAME, ID ,ADDRESS1)
VALUES ('SHARBEL',1,'ABU SINAN')
INSERT INTO CLIENTS  (NAME, ID ,ADDRESS1)
VALUES ('KHLIL',2,'NAHEF')

							/* INSERT TO ACCOUNTS*/
INSERT INTO ACCOUNTS (CLIENT_ID,ACCOUNT_NUM,BALANCE,MSGERT,ACCOUNT_ACTIONS_NUM)
VALUES (11,1,5000,2000,0)
INSERT INTO ACCOUNTS (CLIENT_ID,ACCOUNT_NUM,BALANCE,MSGERT,ACCOUNT_ACTIONS_NUM)
VALUES (22,2,5000,2000,0)

							/* INSERT TO ACTIONS_TYPE*/
INSERT INTO ACTIONS_TYPE (ACTION_NAME,ACTION_CODE,ACTION_COST)
VALUES ('DEPOSIT',1,5)
INSERT INTO ACTIONS_TYPE (ACTION_NAME,ACTION_CODE,ACTION_COST)
VALUES ('WITHDRAW',2,5)
INSERT INTO ACTIONS_TYPE (ACTION_NAME,ACTION_CODE,ACTION_COST)
VALUES ('TRANSFER',3,10)

